import { Box } from "@chakra-ui/react";
import { useRouter } from "next/router";
import { useEffect } from "react";
import { useRecoilValue } from "recoil";
import { authStore } from "../store";
import Head from "next/head";
import { OrganismNavbarContainer } from "../components/organism";

interface AuthorizedLayoutProps {
  children: React.ReactNode;
  title?: string;
}

const AuthorizedLayout: React.FC<AuthorizedLayoutProps> = ({
  children,
  title,
}: AuthorizedLayoutProps) => {
  const { data } = useRecoilValue(authStore.authAtom);
  const router = useRouter();

  useEffect(() => {
    if (!data.token && router.isReady) router.replace("/login");
  }, [data.token, router]);

  return (
    <Box>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <OrganismNavbarContainer>{children}</OrganismNavbarContainer>
    </Box>
  );
};

export default AuthorizedLayout;
