import Head from "next/head";
import { useRouter } from "next/router";
import React, { useEffect } from "react";
import { useRecoilValue } from "recoil";
import { authStore } from "../store";

interface UnauthorizedLayoutProps {
  children: React.ReactNode;
  title: string;
}

const UnauthorizedLayout: React.FC<UnauthorizedLayoutProps> = ({
  children,
  title,
}) => {
  const { data } = useRecoilValue(authStore.authAtom);
  const router = useRouter();

  useEffect(() => {
    if (data.token && router.isReady) router.replace("/");
  }, [data.token, router]);

  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {children}
    </>
  );
};

export default UnauthorizedLayout;
